### ISSUE TITLE
need to fix

### ISSUE THREAD

**Issue by JacksonDon** [TempleDevelopment/TempleWare#1]
cursor is showing... for some reason... (need to fix...)

**Comment by PhilipPanda** [comment]
Thank you for your feedback.

I'm aware of the issue with the cursor and I'm working on it, in terms of the poor font quality i have no idea what you mean as I'm seeing it normally.

**Comment by JacksonDon** [comment]
and hotfix for enemies when you kill 'em, theyre not rendering anymore
