### ISSUE TITLE
Fix mouse cursor

### ISSUE THREAD

**Issue by lwnb666777** [TempleDevelopment/TempleWare#2]
Need to fix mouse cursor keeps showing in the center of the screen

**Comment by lwnb666777** [comment]
Come on, buddy, looking forward to adding more features

**Comment by PhilipPanda** [comment]
Will do. If you want to contribute to the project feel free :)

**Comment by JacksonDon** [comment]
fix for cursor 

            ImGuiIO& io = ImGui::GetIO();
            io.MouseDrawCursor = menu::show; // bool
            io.WantCaptureKeyboard = menu::show;  // bool
            io.WantCaptureMouse = menu::show;  // bool

**Comment by PhilipPanda** [comment]
> fix for cursor 
> 
> 
> 
>             ImGuiIO& io = ImGui::GetIO();
> 
>             io.MouseDrawCursor = menu::show; // bool
> 
>             io.WantCaptureKeyboard = menu::show;  // bool
> 
>             io.WantCaptureMouse = menu::show;  // bool

That's great, mind making a pull request with this fix. As I prefer crediting the person, its a open source project after all 😀
